<?php declare(strict_types=1);
/**
 * Copyright (c) Falcon Media (info@falconmedia.nl)
 *
 * @package Innosend_PickupPoints
 * @author Falcon Media
 * @version 1.0.0
 * @date 2025-11-28
 */

use Innosend\PickupPoints\Block\Checkout\PickupPoint;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var PickupPoint $block */

if (!$block->isEnabled()) {
    return;
}
?>
<div id="innosend-pickup-points-container" 
     data-bind="scope: 'innosendPickupPoints'"
     style="--icon-arrow-path: url('<?= $block->getViewFileUrl('Innosend_PickupPoints::images/icons/arrow-path.svg') ?>');
            --icon-x-mark: url('<?= $block->getViewFileUrl('Innosend_PickupPoints::images/icons/x-mark.svg') ?>');
            --icon-chevron-down: url('<?= $block->getViewFileUrl('Innosend_PickupPoints::images/icons/chevron-down.svg') ?>');
            --icon-chevron-up: url('<?= $block->getViewFileUrl('Innosend_PickupPoints::images/icons/chevron-up.svg') ?>');
            --icon-map-pin: url('<?= $block->getViewFileUrl('Innosend_PickupPoints::images/icons/map-pin.svg') ?>');
            --icon-plus: url('<?= $block->getViewFileUrl('Innosend_PickupPoints::images/icons/plus.svg') ?>');">
    <!-- ko if: selectedPickupPointDisplay() -->
    <!-- ko template: 'Innosend_PickupPoints/pickup-points/selected' --><!-- /ko -->
    <!-- /ko -->

    <!-- ko if: isModalVisible() -->
    <!-- ko template: getTemplate() --><!-- /ko -->
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "#innosend-pickup-points-container": {
        "Magento_Ui/js/core/app": {
            "components": {
                "innosendPickupPoints": {
                    "component": "Innosend_PickupPoints/js/pickup-points",
                    "config": {
                        "ajaxUrl": "<?= $escaper->escapeJs($block->getAjaxUrl()) ?>",
                        "showMap": <?= $block->isMapEnabled() ? 'true' : 'false' ?>,
                        "showMapMobile": <?= $block->isMapEnabledOnMobile() ? 'true' : 'false' ?>,
                        "mapType": "<?= $escaper->escapeJs($block->getMapType()) ?>",
                        "googleMapsApiKey": "<?= $escaper->escapeJs($block->getGoogleMapsApiKey()) ?>",
                        "googleMapsMapId": "<?= $escaper->escapeJs($block->getGoogleMapsMapId()) ?>",
                        "openMapsApiKey": "<?= $escaper->escapeJs($block->getOpenMapsApiKey()) ?>",
                        "allowedCarriers": <?= json_encode($block->getAllowedCarriers()) ?>
                    }
                }
            }
        }
    }
}
</script>
